language: go

go:
  - 1.15.x

env:
  global:
    - VERSION=${TRAVIS_BRANCH}-${TRAVIS_COMMIT}
    - GOPATH=${TRAVIS_BUILD_DIR}/.go
    - GOCACHE=${TRAVIS_BUILD_DIR}/.cache/go-build

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/.go/pkg/mod/
    - ${TRAVIS_BUILD_DIR}/.cache/go-build

script:
  - go mod download
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test -v ./...
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X code.siemens.com/q2qsaa/link-checker-service/infrastructure.Version=$VERSION" -o link-checker-service-lin .
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-X code.siemens.com/q2qsaa/link-checker-service/infrastructure.Version=$VERSION" -o link-checker-service-win.exe .
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-X code.siemens.com/q2qsaa/link-checker-service/infrastructure.Version=$VERSION" -o link-checker-service-osx .
  - ./link-checker-service-lin version
  - ./link-checker-service-lin || true
  - cd $TRAVIS_BUILD_DIR/test/jquery_example && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o $TRAVIS_BUILD_DIR/link-checker-example-ui-lin .
  - cd $TRAVIS_BUILD_DIR/test/jquery_example && CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o $TRAVIS_BUILD_DIR/link-checker-example-ui-win.exe .
  - cd $TRAVIS_BUILD_DIR/test/jquery_example && CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o $TRAVIS_BUILD_DIR/link-checker-example-ui-osx .
  - cp $TRAVIS_BUILD_DIR/test/jquery_example/start_example.bat $TRAVIS_BUILD_DIR/
