language: go
go:
- 1.15.x
script:
  ./travis_build.sh
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - ls -rtla
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: mb/CIE4ujKCJAKNoHFPVsslUd+5mJp2VoIkjghbmcUfBcG92wugDeIIq+JiAdDiNdr1VgfnAHeZDMvxiB+/dzCY9POTq8nyR9EhZtvKqxCdG9L5ua0iV8i55JrN1g6c5RC7l22jf6ix8LqXqxmlBkG6kQ2j/s/jzVcFDntIfamxdUU99i2LS8l4XYR3/J9fd243/TLPriMgkpuOO0lyQ3ItFPRp9IAJdg5RZOtAJDUZTqM9+qrk9XNXG8Ee3SSXm5SA2wsAfqr222CxIhUkMD1KSp8bzH8Pa59bZDr1N8h+2JntVr64tRGbsX0CAYry3OypgcYqFMj7gZvxwBC2eyubZU/jCGq6k42pAboTZHelum1BwfOXvyLIImGpJg/LOtSjou2wZAzvsPK0Dqw36YRUxSyUsQ/77U2z4DX/lRTQZbtZ4RASUsTLE5DIos+lYlx+Zqp/B8ZJavN8UrAeKbuG2GjdwJWpeofKIE2XMu3P4EnoKke2kXqEbGTdk8iAEmPui79b1hMLQ0FZjKPw4BQqPESDTVYWUVu0nkha61AfCNt+HmuWFFjDn+CFr6HeBjXlRJo42rh0Mbul1hJ58rOwBzcA4jx7046jxPaVbWgb+ADnGmuzgCvX+NeJP+x6weBPk9fisW3+s8xyYSxZAbJdcNnRN40bL99eMpIBHauA=
  file:
    - link-checker-service-lin.tgz
    - link-checker-service-win.zip
    - link-checker-service-osx.tgz
  on:
    repo: siemens/link-checker-service
    tags: true
