# https://github.com/goreleaser/goreleaser-action
name: Release

on:
    push:
        tags:
            - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
      -
        name: Build & Package
        run: ./github_build.sh
      -
        uses: ncipollo/release-action@v1
        with:
          artifacts: "link-checker-service-lin.tgz,link-checker-service-osx.tgz,link-checker-service-win.zip"
          body: "see [CHANGES](CHANGES.md)"
          token: ${{ secrets.GITHUB_TOKEN }}
