# https://github.com/goreleaser/goreleaser-action
name: Release

on:
    push:
        tags:
            - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Build & Package
        run: ./github_build.sh
      -
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            link-checker-service-lin.tgz
            link-checker-service-osx.tgz
            link-checker-service-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
